# Generated by Django 5.2.17 on 2026-09-09 05:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geofence_radius_meters', models.FloatField(default=50.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('IDLE', 'Idle'), ('MOVING', 'Moving'), ('CHECKED_IN', 'Checked In')], default='OFF_DUTY', max_length=20)),
                ('battery_level', models.IntegerField(default=100)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_speed', models.FloatField(default=0.0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.FloatField()),
                ('check_in_longitude', models.FloatField()),
                ('distance_at_checkin', models.FloatField(help_text='Exact distance from client geofence center in meters at check-in')),
                ('meeting_notes', models.TextField(blank=True)),
                ('order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visit_photos/')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tracking.agentprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tracking.clientlocation')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='LocationTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0.0)),
                ('battery_level', models.IntegerField(default=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='tracking.agentprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='tracking_lo_agent_i_ff668b_idx')],
            },
        ),
    ]
