# Generated by Django 5.2.17 on 2026-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='attachment_image',
            field=models.TextField(blank=True, default='', help_text='Discussion attachment image (base64 or URL)'),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='selfie_image',
            field=models.TextField(blank=True, default='', help_text='Watermarked selfie punch image (base64 or URL)'),
        ),
    ]
